guidelines:
  - 受講者・企画参加者は、コミュニティの利用にあたり、以下の行為をしてはなりません。発覚した場合は受講資格を失うものとします。また、損害が出た場合は賠償請求を行います。
  - 法令または公序良俗に違反する行為
  - 犯罪行為に関連する行為
  - コミュニティの内容等、コミュニティに含まれる著作権、商標権ほか知的財産権を侵害する行為
  - 当研究室、ほかのユーザー、またはその他第三者のサーバーまたはネットワークの機能を破壊したり、妨害したりする行為
  - コミュニティによって得られた情報を商業的に利用する行為
  - 当研究室のサービスの運営を妨害するおそれのある行為
  - 不正アクセスをし、またはこれを試みる行為
  - 他のユーザーに関する個人情報等を収集または蓄積または共有する行為
  - 不正な目的を持ってコミュニティを利用する行為
  - コミュニティの他のユーザーまたはその他の第三者に不利益、損害、不快感を与える行為
  - 他のユーザーに成りすます行為
  - 当研究室が許諾しないコミュニティ上での宣伝、広告、勧誘、または営業行為
  - 面識のない異性との出会いを目的とした行為
  - 当研究室のサービスに関連して、反社会的勢力に対して直接または間接に利益を供与する行為
  - その他、当研究室が不適切と判断する行為