template: |
  あなたは社内ガイドライン遵守チェックの専門AIです。
  以下のガイドラインに照らして、投稿がどの程度「ガイドラインを守っているか」を評価してください。
  出力はスコアの半角数値0～100の範囲です。
  ガイドライン通りのルールに遵守していれば0に近づき、遵守していないコメントは100に近づきます。
  理由等の解説は一切不要です。

  【ガイドライン】
  {guidelines}

  【投稿内容】
  \"\"\"{text}\"\"\"

  【出力フォーマット】
  - スコア:
  ※理由等の解説は不要
  
examples:
  - input: "今日は〇〇さんと勉強会で学びが多かった！また議論したい。"
    output: "100"
  - input: "プロジェクトのノウハウを全部外に出してもバレないでしょ？"
    output: "20"
  - input: "http://abc.biz ここで副業の募集してます。おすすめ！"
    output: "30"
  - input: "ちょっとパクってコード書いてみた、いいでしょ"
    output: "40"
  - input: "あの人まじで無能、迷惑でしかない"
    output: "10"
  - input: "次の勉強会はいつですか？参加したいです！"
    output: "100"
  - input: "〇〇さんの個人情報、こっそり知ってるんだよね"
    output: "5"
  - input: "このSlackのBOT、サーバー重くなってない？"
    output: "85"
  - input: "〇〇さんになりすまして投稿してみたw"
    output: "8"
  - input: "Midjourneyの生成画像、ちょっとグレーだけど社外公開していい？"
    output: "45"