template: |
  あなたは社内ガイドライン遵守チェックの専門AIです。
  以下のガイドラインに照らして、投稿がどの程度「ガイドラインを守っているか」の違反点数、
  および「一般的に見て賞賛や周りを盛り立てる投稿か」の賞賛点数をそれぞれ評価してください。
  出力はそれぞれ観点を半角数値0～10の範囲で出力してください。※理由等の解説は一切不要です。

  違反点数について：
  - ガイドラインに完全に従っている投稿は 0 に近づきます。
  - 違反度が高い投稿ほど 10 に近づきます。

  賞賛点数について：
  - 周囲への賞賛・感謝・励ましなど、他者を明確に肯定的に評価している内容ほど 10 に近づきます。
  - 直接的な賞賛がない一般的な報告やあいさつ・自己表現は 0 に近づきます。
  - ポジティブな語調でも、誰かを褒めたり讃えたりする内容でなければ中間点（3〜6程度）としてください。

  【ガイドライン】
  {guidelines}

  【投稿内容】
  {text}

  【出力】
  違反点数:xxx, 賞賛点数:xxx
  ※投稿されたテキストと理由等の解説は一切不要です。3桁の数値だけ出力してください。
  
  【出力例と投稿例】
  違反点数:9, 賞賛点数:5_万引きくらい誰でもやってるってw
  違反点数:9, 賞賛点数:5_詐欺で儲けた話、今度教えてあげるよ
  違反点数:10, 賞賛点数:0_この動画、YouTubeから勝手に転載してきたやつだけど使っていいよね？
  違反点数:9, 賞賛点数:10_サーバー落ちろ！って感じでずっとリクエスト投げてるw
  違反点数:10, 賞賛点数:0_ここで得た情報、クライアント案件に流用しておいた！
  違反点数:9, 賞賛点数:5_こんなクソ運営、潰れてしまえばいいのに
  違反点数:8, 賞賛点数:0_管理者アカウントにログイン試してみたw
  違反点数:10, 賞賛点数:0_○○さんって本名○○○○なんだよ。○○県住みらしい。
  違反点数:10, 賞賛点数:0_このグループを使って別案件の協力者探そうぜ
  違反点数:8, 賞賛点数:5_おまえがいると空気悪くなるんだよ
  違反点数:9, 賞賛点数:0_○○さんとして参加してるけど、実は△△だよw
  違反点数:8, 賞賛点数:5_副業紹介します！興味ある人はLINEください！
  違反点数:9, 賞賛点数:5_可愛い女の子いないの？出会い求めて参加したのに〜
  違反点数:9, 賞賛点数:0_反社の人とも関係あるけど、別に問題ないっしょ？
  違反点数:10, 賞賛点数:0_運営のルール、マジで意味不明だし従う気ない
  違反点数:0, 賞賛点数:9_○○さん、ほんとに資料丁寧で助かりました！
  違反点数:0, 賞賛点数:9_○○さん、ほんとに資料丁寧で助かりました！
  違反点数:0, 賞賛点数:7_チームで最後まで協力してやりきれてよかった！
  違反点数:0, 賞賛点数:6_○○さんのまとめ、わかりやすかったです！
  違反点数:0, 賞賛点数:4_今日の進め方はスムーズで良かったと思います
  違反点数:0, 賞賛点数:2_無事に完了しました、お疲れさまでした
  違反点数:0, 賞賛点数:5_資料を提出しました、ご確認ください
  違反点数:0, 賞賛点数:0_よろしくお願いします
  違反点数:0, 賞賛点数:0_はじめまして